apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  labels:
    app: webapp
  namespace: webapp
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.health-check-path: "/health"
    kubernetes.io/ingress.global-static-ip-name: "service-ip"
    networking.gke.io/managed-certificates: "service-ssl"
    kubernetes.io/ingress.force-ssl-redirect: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  ingressClassName: gce
  rules:
  - host: host
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp-service
            port:
              number: 80
  - host: www.host
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp-service
            port:
              number: 80