apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  namespace: webapp
data:  
  DATABASE_SERVER: "mssql-service.mssql.svc.cluster.local"
  DATABASE_PORT: "1433"
  DATABASE_NAME: "BukharaTravel"
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"