apiVersion: v1
apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
  namespace: webapp
type: Opaque
data:
  SA_PASSWORD: UEFTU1dPUkQ=
  DATABASE_USER: VVNFUg==
  DATABASE_PASSWORD: UEFTU1dPUkQ=